application: leprechaunpot-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /favicon\.ico
  static_files: /static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: /asciitube
  static_dir: asciitube/static

- url: /gatekeeper/static
  static_dir: gatekeeper/static

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

