handlers:

- url: /favicon\.ico
  static_files: /static/favicon.ico
  upload: static/favicon\.ico

- url: /static
  static_dir: static

- url: /asciitube
  static_dir: asciitube/static

- url: /crowddj/static
  static_dir: crowddj/static

- url: /gatekeeper/static
  static_dir: gatekeeper/static

- url: /postasokoban/static
  static_dir: postasokoban/static

- url: /fixture/static
  static_dir: fixture/static

- url: /fixture/?.*
  script: fixture.controller.app

- url: /.*
  script: main.app

#- url: /.*
#  static_files: templates/404.html
#  upload: templates/404\.html

